/* Generated by re2c 2.0.3 on Mon Dec 14 07:22:42 2020 */
// re2c $INPUT -o $OUTPUT -i
// french : https://fr.qaz.wiki/wiki/Re2c
// english : https://wikivisually.com/wiki/re2c
// https://www.systutorials.com/docs/linux/man/1-re2c

int lex(const char *YYCURSOR)
{
    int wordCount = 0; // count word, not letters
loop:
    
{
	char yych;
	yych = *current_char;
	switch (yych) {
	case 0x00: goto yy2;
	case '\t' ... '\n':
	case '\r': goto yy6;
	case ' ': goto yy8;
	case ',': goto yy9;
	case 'a' ... 'q':
	case 's' ... 'z': goto yy11;
	case 'r': goto yy14;
	default: goto yy4;
	}
yy2:
	++current_char;
	{ return wordCount; }
yy4:
	++current_char;
	{ printf("err\n"); return -1; }
yy6:
	++current_char;
yy7:
	{ goto loop;}
yy8:
	yych = *++current_char;
	switch (yych) {
	case ' ': goto yy15;
	default: goto yy7;
	}
yy9:
	++current_char;
	{ return(","); }
yy11:
	yych = *++current_char;
yy12:
	switch (yych) {
	case 'a' ... 'z': goto yy11;
	default: goto yy13;
	}
yy13:
	{ ++wordCount; goto loop; }
yy14:
	yych = *++current_char;
	switch (yych) {
	case 'e': goto yy18;
	default: goto yy12;
	}
yy15:
	yych = *++current_char;
	switch (yych) {
	case ' ': goto yy15;
	default: goto yy17;
	}
yy17:
	{ goto loop; }
yy18:
	yych = *++current_char;
	switch (yych) {
	case 's': goto yy19;
	default: goto yy12;
	}
yy19:
	yych = *++current_char;
	switch (yych) {
	case 'e': goto yy20;
	default: goto yy12;
	}
yy20:
	yych = *++current_char;
	switch (yych) {
	case 't': goto yy21;
	default: goto yy12;
	}
yy21:
	yych = *++current_char;
	switch (yych) {
	case 'a' ... 'z': goto yy11;
	default: goto yy22;
	}
yy22:
	{ printf("Reset ....");wordCount=0;return 0; }
}

    
    /*ident = [a-zA-Z_][a-zA-Z_0-9]*; // named definition
    ident { return 0; }*/
    //assert(lex("") == 0);
    //assert(lex("one two three") == 3);
    //assert(lex("f0ur") == -1);
}
