/* Generated by re2c 2.0.3 on Mon Dec 28 23:29:37 2020 */
/*Configurations section*/
#include "parser.h"

// C/C++ code
int lex(const char *YYCURSOR)
{
    
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ': goto yy5;
	case '"':
	case '\'': goto yy7;
	case '$': goto yy9;
	case ')': goto yy10;
	case '-' ... '9':
	case 'A' ... 'Z':
	case '_':
	case 'a' ... 'z': goto yy12;
	case '|': goto yy15;
	default: goto yy2;
	}
yy2:
	yych = *++YYCURSOR;
yy3:
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy4;
	default: goto yy2;
	}
yy4:
	{return ARGUMENT;}
yy5:
	++YYCURSOR;
	{}
yy7:
	++YYCURSOR;
	{ return -1; }
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case '(': goto yy17;
	default: goto yy3;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy11;
	default: goto yy2;
	}
yy11:
	{return COMMAND_SUBSTITUTION_END;}
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy14;
	case '-' ... '9':
	case 'A' ... 'Z':
	case '_':
	case 'a' ... 'z': goto yy12;
	default: goto yy2;
	}
yy14:
	{return FILENAME;}
yy15:
	++YYCURSOR;
	{return PIPE;}
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy18;
	default: goto yy2;
	}
yy18:
	{return COMMAND_SUBSTITUTION_START;}
}

}
