#define TK_DEFAULT                          1
#define TK_BREAK                            2
#define TK_RETURN                           3
#define TK_FALLTHROUGH                      4
#define TK_SEMCOL                           5
#define TK_FOR                              6
#define TK_SWITCH                           7
#define TK_IF                               8
#define TK_VARTYPE                          9
#define TK_IDENTIFIER                      10
#define TK_ASSIGN                          11
#define TK_AND                             12
#define TK_OR                              13
#define TK_EQ                              14
#define TK_NE                              15
#define TK_GT                              16
#define TK_GE                              17
#define TK_LT                              18
#define TK_LE                              19
#define TK_ADD                             20
#define TK_SUB                             21
#define TK_MUL                             22
#define TK_DIV                             23
#define TK_MOD                             24
#define TK_POS                             25
#define TK_NEG                             26
#define TK_LBRACKET                        27
#define TK_RBRACKET                        28
#define TK_LPAREN                          29
#define TK_RPAREN                          30
#define TK_EXP                             31
#define TK_NOT                             32
#define TK_END_OF_LINE                     33
#define TK_END_OF_FILE                     34
#define TK_STAR_ASSIGN                     35
#define TK_DIV_ASSIGN                      36
#define TK_MOD_ASSIGN                      37
#define TK_ADD_ASSIGN                      38
#define TK_SUB_ASSIGN                      39
#define TK_LEFT_ASSIGN                     40
#define TK_RIGHT_ASSIGN                    41
#define TK_AND_ASSIGN                      42
#define TK_XOR_ASSIGN                      43
#define TK_OR_ASSIGN                       44
#define TK_VOID                            45
#define TK_CHAR                            46
#define TK_SHORT                           47
#define TK_INT                             48
#define TK_LONG                            49
#define TK_FLOAT                           50
#define TK_DOUBLE                          51
#define TK_SIGNED                          52
#define TK_UNSIGNED                        53
#define TK_TYPE_NAME                       54
#define TK_STRUCT                          55
#define TK_UNION                           56
#define TK_CONSTANT                        57
#define TK_STRING_LITERAL                  58
#define TK_COMMA                           59
#define TK_LSQUAREB                        60
#define TK_RSQUAREB                        61
#define TK_ELLIPSIS                        62
#define TK_ELSE                            63
#define TK_CONTINUE                        64
#define TK_ENUM                            65
#define TK_DOT                             66
#define TK_INC_OP                          67
#define TK_DEC_OP                          68
#define TK_REF                             69
#define TK_STAR                            70
#define TK_PLUS                            71
#define TK_MINUS                           72
#define TK_TILDE                           73
#define TK_SIZEOF                          74
