#define TK_IDENTIFIER                       1
#define TK_CONSTANT                         2
#define TK_STRING_LITERAL                   3
#define TK_SIZEOF                           4
#define TK_PTR_OP                           5
#define TK_INC_OP                           6
#define TK_DEC_OP                           7
#define TK_LEFT_OP                          8
#define TK_RIGHT_OP                         9
#define TK_LE_OP                           10
#define TK_GE_OP                           11
#define TK_EQ_OP                           12
#define TK_NE_OP                           13
#define TK_AND_OP                          14
#define TK_OR_OP                           15
#define TK_STAR_ASSIGN                     16
#define TK_DIV_ASSIGN                      17
#define TK_MOD_ASSIGN                      18
#define TK_ADD_ASSIGN                      19
#define TK_SUB_ASSIGN                      20
#define TK_LEFT_ASSIGN                     21
#define TK_RIGHT_ASSIGN                    22
#define TK_AND_ASSIGN                      23
#define TK_XOR_ASSIGN                      24
#define TK_OR_ASSIGN                       25
#define TK_TYPE_NAME                       26
#define TK_TYPEDEF                         27
#define TK_EXTERN                          28
#define TK_STATIC                          29
#define TK_AUTO                            30
#define TK_REGISTER                        31
#define TK_CHAR                            32
#define TK_SHORT                           33
#define TK_INT                             34
#define TK_LONG                            35
#define TK_SIGNED                          36
#define TK_UNSIGNED                        37
#define TK_FLOAT                           38
#define TK_DOUBLE                          39
#define TK_CONST                           40
#define TK_VOLATILE                        41
#define TK_VOID                            42
#define TK_STRUCT                          43
#define TK_UNION                           44
#define TK_ENUM                            45
#define TK_ELLIPSIS                        46
#define TK_CASE                            47
#define TK_DEFAULT                         48
#define TK_IF                              49
#define TK_ELSE                            50
#define TK_SWITCH                          51
#define TK_WHILE                           52
#define TK_DO                              53
#define TK_FOR                             54
#define TK_GOTO                            55
#define TK_CONTINUE                        56
#define TK_BREAK                           57
#define TK_RETURN                          58
#define TK_END_OF_LINE                     59
#define TK_END_OF_FILE                     60
#define TK_LPAREN                          61
#define TK_RPAREN                          62
#define TK_LSQUAREB                        63
#define TK_RSQUAREB                        64
#define TK_DOT                             65
#define TK_COMMA                           66
#define TK_REF                             67
#define TK_STAR                            68
#define TK_PLUS                            69
#define TK_MINUS                           70
#define TK_TILDE                           71
#define TK_NOT                             72
#define TK_DIV                             73
#define TK_MOD                             74
#define TK_LT                              75
#define TK_GT                              76
#define TK_XOR                             77
#define TK_PIPE                            78
#define TK_QUESTION                        79
#define TK_COLON                           80
#define TK_ASSIGN                          81
#define TK_SEMCOL                          82
#define TK_LBRACKET                        83
#define TK_RBRACKET                        84
