#define TK_IDENTIFIER                       1
#define TK_CONSTANT                         2
#define TK_STRINGLITERAL                    3
#define TK_LPAREN                           4
#define TK_RPAREN                           5
#define TK_LSQUAREBRACKET                   6
#define TK_RSQUAREBRACKET                   7
#define TK_DOT                              8
#define TK_ARROW                            9
#define TK_PLUSPLUS                        10
#define TK_MINUSMINUS                      11
#define TK_EQ                              12
#define TK_MULEQ                           13
#define TK_DIVEQ                           14
#define TK_MODEQ                           15
#define TK_PLUSEQ                          16
#define TK_MINUSEQ                         17
#define TK_LSHIFTEQ                        18
#define TK_RSHIFTEQ                        19
#define TK_ANDEQ                           20
#define TK_EXPEQ                           21
#define TK_OREQ                            22
#define TK_VALUE                           23
