/* Generated by re2c 2.0.3 on Sun Dec 13 10:08:31 2020 */
#line 1 "scanner.re2c"
// re2c $INPUT -o $OUTPUT -i

/*Configurations section*/
#include <assert.h>
#include "parser.h"

// C/C++ code
int lex(const char *YYCURSOR)
{
    
#line 14 "scanner.re2c.h"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ': goto yy5;
	case '"':
	case '\'': goto yy7;
	case '$': goto yy9;
	case ')': goto yy10;
	case '-' ... '9':
	case 'A' ... 'Z':
	case '_':
	case 'a' ... 'z': goto yy12;
	case '|': goto yy15;
	default: goto yy2;
	}
yy2:
	yych = *++YYCURSOR;
yy3:
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy4;
	default: goto yy2;
	}
yy4:
#line 22 "scanner.re2c"
	{return ARGUMENT;}
#line 48 "scanner.re2c.h"
yy5:
	++YYCURSOR;
#line 18 "scanner.re2c"
	{}
#line 53 "scanner.re2c.h"
yy7:
	++YYCURSOR;
#line 26 "scanner.re2c"
	{ return -1; }
#line 58 "scanner.re2c.h"
yy9:
	yych = *++YYCURSOR;
	switch (yych) {
	case '(': goto yy17;
	default: goto yy3;
	}
yy10:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy11;
	default: goto yy2;
	}
yy11:
#line 17 "scanner.re2c"
	{return COMMAND_SUBSTITUTION_END;}
#line 79 "scanner.re2c.h"
yy12:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy14;
	case '-' ... '9':
	case 'A' ... 'Z':
	case '_':
	case 'a' ... 'z': goto yy12;
	default: goto yy2;
	}
yy14:
#line 19 "scanner.re2c"
	{return FILENAME;}
#line 98 "scanner.re2c.h"
yy15:
	++YYCURSOR;
#line 15 "scanner.re2c"
	{return PIPE;}
#line 103 "scanner.re2c.h"
yy17:
	yych = *++YYCURSOR;
	switch (yych) {
	case '\t' ... '\n':
	case '\r':
	case ' ':
	case '"':
	case '\'':
	case '|': goto yy18;
	default: goto yy2;
	}
yy18:
#line 16 "scanner.re2c"
	{return COMMAND_SUBSTITUTION_START;}
#line 118 "scanner.re2c.h"
}
#line 27 "scanner.re2c"

}

int main()
{
    assert(lex("_Zer0") == 0);
    return 0;
}
